name: TS compilation

concurrency:
  group: wf-${{github.event.pull_request.number || github.sha}}-${{github.workflow}}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - "[0-9][0-9].[0-9].[0-9]*"

jobs:
  webpack-jquery:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Get sources
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Restore npm cache
      uses: actions/cache@v4
      with:
        path: ./webpack-jquery/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('webpack-jquery/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules

    - name: Run npm install
      working-directory: webpack-jquery
      run: npm install --no-audit --no-fund

    - name: Build webpack-jquery
      working-directory: webpack-jquery
      run: npm run build

  webpack-react:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Get sources
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Restore npm cache
      uses: actions/cache@v4
      with:
        path: ./webpack-react/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('webpack-react/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules

    - name: Run npm install
      working-directory: webpack-react
      run: npm install --no-audit --no-fund

    - name: Build webpack-react
      working-directory: webpack-react
      run: npm run build

  webpack-vue:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Get sources
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Restore npm cache
      uses: actions/cache@v4
      with:
        path: ./webpack-vue/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('webpack-vue/package-lock.json') }}
        restore-keys: ${{ runner.os }}-node-modules

    - name: Run npm install
      working-directory: webpack-vue
      run: npm install --no-audit --no-fund

    - name: Build webpack-vue
      working-directory: webpack-vue
      run: npm run build
